//! Generated by scripts/port_upstream_csharp.py. Do not edit by hand.

pub const UPSTREAM_COMMIT: &str = "1f0fd1930d14653b9a041f325a952cd23d336c51";
pub const SOURCE_DIGEST: &str = "125c2ff535a23ca258706c3d9dc8d7df5cd413e7a4a8ad98b4c217796ca19a0e";

pub const UPSTREAM_COMMANDS: &[&str] = &[
    "__resident-serve__",
    "add",
    "add-part",
    "batch",
    "close",
    "create",
    "dump",
    "get",
    "help",
    "import",
    "info",
    "lint",
    "list",
    "merge",
    "move",
    "open",
    "plugins",
    "query",
    "raw",
    "raw-set",
    "refresh",
    "remove",
    "save",
    "set",
    "swap",
    "unwatch",
    "validate",
    "view",
    "watch",
];

pub const RUST_COMMANDS: &[&str] = &[
    "add",
    "add-part",
    "batch",
    "close",
    "create",
    "dump",
    "get",
    "get-part",
    "inspect",
    "list-parts",
    "merge",
    "move",
    "open",
    "query",
    "raw",
    "raw-set",
    "remove",
    "remove-part",
    "save",
    "set",
    "set-part",
    "swap",
    "validate",
    "view",
];

pub const MISSING_RUST_COMMANDS: &[&str] = &[
    "__resident-serve__",
    "help",
    "import",
    "info",
    "lint",
    "list",
    "plugins",
    "refresh",
    "unwatch",
    "watch",
];

pub fn supports(command: &str) -> bool {
    RUST_COMMANDS.binary_search(&command).is_ok()
}
