//! Generated by scripts/port_upstream_csharp.py. Do not edit by hand.

pub const UPSTREAM_COMMIT: &str = "e43aebd7f4cff79a8027d13f54dbafe2f550199e";
pub const SOURCE_DIGEST: &str = "970a3877e540e1e638fdd3f5b3d80e6c7b80bb9e36198b7b7df58fc54ebf5c48";

pub const UPSTREAM_COMMANDS: &[&str] = &[
    "__resident-serve__",
    "add",
    "add-part",
    "batch",
    "close",
    "create",
    "dump",
    "get",
    "help",
    "import",
    "info",
    "lint",
    "list",
    "merge",
    "move",
    "open",
    "plugins",
    "query",
    "raw",
    "raw-set",
    "refresh",
    "remove",
    "save",
    "set",
    "swap",
    "unwatch",
    "validate",
    "view",
    "watch",
];

pub const RUST_COMMANDS: &[&str] = &[
    "add",
    "add-part",
    "batch",
    "close",
    "create",
    "dump",
    "get",
    "get-part",
    "inspect",
    "list-parts",
    "merge",
    "move",
    "open",
    "query",
    "raw",
    "raw-set",
    "remove",
    "remove-part",
    "save",
    "set",
    "set-part",
    "swap",
    "validate",
    "view",
];

pub const MISSING_RUST_COMMANDS: &[&str] = &[
    "__resident-serve__",
    "help",
    "import",
    "info",
    "lint",
    "list",
    "plugins",
    "refresh",
    "unwatch",
    "watch",
];

pub fn supports(command: &str) -> bool {
    RUST_COMMANDS.binary_search(&command).is_ok()
}
