//! Generated by scripts/port_upstream_csharp.py. Do not edit by hand.

pub const UPSTREAM_COMMIT: &str = "4ba79f0b984e141f57f58d4398ba2df29e8187e8";
pub const SOURCE_DIGEST: &str = "c799c244c89b0e0d4524753dcbad1dcd88bcd6e65004c58d65787ae21f8de3dc";

pub const UPSTREAM_COMMANDS: &[&str] = &[
    "__resident-serve__",
    "add",
    "add-part",
    "batch",
    "close",
    "create",
    "dump",
    "get",
    "help",
    "import",
    "info",
    "lint",
    "list",
    "merge",
    "move",
    "open",
    "plugins",
    "query",
    "raw",
    "raw-set",
    "refresh",
    "remove",
    "save",
    "set",
    "swap",
    "unwatch",
    "validate",
    "view",
    "watch",
];

pub const RUST_COMMANDS: &[&str] = &[
    "add",
    "add-part",
    "batch",
    "close",
    "create",
    "dump",
    "get",
    "get-part",
    "inspect",
    "list-parts",
    "merge",
    "move",
    "open",
    "query",
    "raw",
    "raw-set",
    "remove",
    "remove-part",
    "save",
    "set",
    "set-part",
    "swap",
    "validate",
    "view",
];

pub const MISSING_RUST_COMMANDS: &[&str] = &[
    "__resident-serve__",
    "help",
    "import",
    "info",
    "lint",
    "list",
    "plugins",
    "refresh",
    "unwatch",
    "watch",
];

pub fn supports(command: &str) -> bool {
    RUST_COMMANDS.binary_search(&command).is_ok()
}
