#!/usr/bin/env python3
"""Generate the Rust compatibility layer from an OfficeCLI C# checkout.

This intentionally generates metadata and compileable Rust, rather than trying
to rewrite arbitrary C# methods with regular expressions. Behavioural changes
still require a reviewed Rust implementation.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path


COMMAND_RE = re.compile(r'new\s+Command\s*\(\s*"([^"]+)"')
TYPE_RE = re.compile(
    r"\b(?:class|record|struct|enum|interface)\s+([A-Za-z_][A-Za-z0-9_]*)"
)
RUST_VARIANT_RE = re.compile(r"^\s{4}([A-Z][A-Za-z0-9_]*)\s*(?:\{|,)", re.MULTILINE)


def kebab_case(value: str) -> str:
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", value)
    return value.replace("_", "-").lower()


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def collect_source(source: Path):
    commands: set[str] = set()
    types: set[str] = set()
    files: list[dict[str, str]] = []
    digest = hashlib.sha256()

    for path in sorted(source.rglob("*.cs")):
        relative = path.relative_to(source).as_posix()
        content = path.read_bytes()
        digest.update(relative.encode("utf-8"))
        digest.update(b"\0")
        digest.update(content)
        text = content.decode("utf-8", errors="replace")
        commands.update(COMMAND_RE.findall(text))
        types.update(TYPE_RE.findall(text))
        files.append(
            {
                "path": relative,
                "sha256": hashlib.sha256(content).hexdigest(),
            }
        )

    return sorted(commands), sorted(types), files, digest.hexdigest()


def rust_commands(cli_source: Path) -> list[str]:
    text = cli_source.read_text(encoding="utf-8")
    match = re.search(
        r"enum\s+Command\s*\{(?P<body>.*?)^\}",
        text,
        re.MULTILINE | re.DOTALL,
    )
    if not match:
        raise SystemExit(f"cannot find Rust Command enum in {cli_source}")
    return sorted(
        {kebab_case(name) for name in RUST_VARIANT_RE.findall(match.group("body"))}
    )


def write_rust_module(
    path: Path, commit: str, commands: list[str], rust: list[str], digest: str
) -> None:
    missing = sorted(set(commands) - set(rust))
    lines = [
        "//! Generated by scripts/port_upstream_csharp.py. Do not edit by hand.",
        "",
        f"pub const UPSTREAM_COMMIT: &str = {rust_string(commit)};",
        f"pub const SOURCE_DIGEST: &str = {rust_string(digest)};",
        "",
        "pub const UPSTREAM_COMMANDS: &[&str] = &[",
    ]
    lines.extend(f"    {rust_string(command)}," for command in commands)
    lines.extend(["];", "", "pub const RUST_COMMANDS: &[&str] = &["])
    lines.extend(f"    {rust_string(command)}," for command in rust)
    lines.extend(["];", "", "pub const MISSING_RUST_COMMANDS: &[&str] = &["])
    lines.extend(f"    {rust_string(command)}," for command in missing)
    lines.extend(
        [
            "];",
            "",
            "pub fn supports(command: &str) -> bool {",
            "    RUST_COMMANDS.binary_search(&command).is_ok()",
            "}",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_report(
    path: Path,
    commit: str,
    commands: list[str],
    rust: list[str],
    types: list[str],
    files: list[dict[str, str]],
    digest: str,
) -> None:
    missing = sorted(set(commands) - set(rust))
    report = {
        "upstream_commit": commit,
        "source_digest": digest,
        "csharp_files": files,
        "csharp_type_count": len(types),
        "upstream_commands": commands,
        "rust_commands": rust,
        "missing_rust_commands": missing,
    }
    path.mkdir(parents=True, exist_ok=True)
    (path / "compatibility.json").write_text(
        json.dumps(report, indent=2) + "\n", encoding="utf-8"
    )
    missing_text = "\n".join(f"- {command}" for command in missing) or "- None"
    (path / "PORT_STATUS.md").write_text(
        "# Generated C# to Rust port status\n\n"
        "This directory is generated by CI from the upstream OfficeCLI C# source. "
        "The Rust compatibility module is compileable and records the upstream "
        "command surface; it does not mechanically rewrite C# business logic.\n\n"
        f"- Upstream commit: {commit}\n"
        f"- C# files: {len(files)}\n"
        f"- C# types discovered: {len(types)}\n"
        f"- Upstream commands: {len(commands)}\n"
        f"- Rust commands: {len(rust)}\n\n"
        "## Commands still requiring Rust implementation\n\n"
        f"{missing_text}\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument(
        "--rust-cli",
        type=Path,
        default=Path("crates/officecli-cli/src/main.rs"),
    )
    parser.add_argument(
        "--rust-module",
        type=Path,
        default=Path("crates/officecli-core/src/upstream_compat.rs"),
    )
    parser.add_argument(
        "--report-dir",
        type=Path,
        default=Path("upstream/officecli-rust"),
    )
    parser.add_argument("--commit", default="unknown")
    args = parser.parse_args()

    commands, types, files, digest = collect_source(args.source)
    rust = rust_commands(args.rust_cli)
    write_rust_module(args.rust_module, args.commit, commands, rust, digest)
    write_report(args.report_dir, args.commit, commands, rust, types, files, digest)
    print(f"generated Rust compatibility metadata for {len(commands)} upstream commands")


if __name__ == "__main__":
    main()
